version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - noctx
    - sqlclosecheck
    - unconvert
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: false
    misspell:
      locale: GB
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - errcheck
        path: internal/.*_test\.go
      - linters:
          - errcheck
        path: internal/http/handlers.go
      - linters:
          - errcheck
          - gosec
        path: internal/parser/*.
      - linters:
          - gosec
        path: internal/testing/
    paths:
      - third_party$
      - builtin$
      - examples$
      - e2e$
      - build£
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/captainmango/coco-cron-parser
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
