# https://taskfile.dev

version: '3'

vars:
  IMAGE_PATH: "./build/docker/Dockerfile"
  IMAGE_TAG: "coco-task-manager"

tasks:
  build-image:
    desc: Build the Docker image for the application
    cmds:
      - docker build -t {{.IMAGE_TAG}}:latest -f {{.IMAGE_PATH}} .
    silent: true

  start-shell:
    desc: Start a container and shell session inside it
    cmds:
      - docker run -it {{.IMAGE_TAG}} sh
    silent: true
  
  push-image:
    desc: Push image to registry
    cmds: 
      - echo 'pushing image to GitHub'
    silent: true

  lint:
    desc: Run the linter
    cmds:
      - golangci-lint run -c .golangci.yml
    silent: true
  
  format:
    desc: Run the linter
    cmds:
      - golangci-lint fmt -c .golangci.yml
    silent: true